(cl:in-package esr_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          SCAN_INDEX-VAL
          SCAN_INDEX
          IS_COMM_ERROR-VAL
          IS_COMM_ERROR
          IS_RADIATING-VAL
          IS_RADIATING
          IS_FAILED-VAL
          IS_FAILED
          IS_BLOCKED-VAL
          IS_BLOCKED
          IS_OVERHEATING-VAL
          IS_OVERHEATING
          IS_RAW_DATA_MODE-VAL
          IS_RAW_DATA_MODE
          INTERNAL_TEMPERATURE-VAL
          INTERNAL_TEMPERATURE
          SW_VERSION-VAL
          SW_VERSION
          IS_LR_ENABLED-VAL
          IS_LR_ENABLED
          IS_MR_ENABLED-VAL
          IS_MR_ENABLED
          IS_SIDELOBE_BLOCKAGE-VAL
          IS_SIDELOBE_BLOCKAGE
          IS_PARTIAL_BLOCKAGE-VAL
          IS_PARTIAL_BLOCKAGE
))